Repository StefanGreve/website, pull requests merged in 2023-12, with the labels that each got.

#6 Dropdown Component
  .editorconfig
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/code-line/code-line.component.html
  src/app/components/code-line/code-line.component.scss
  src/app/components/code-line/code-line.component.ts
  src/app/components/dialog/dialog.component.scss
  src/app/components/dialog/dialog.component.ts
  src/app/components/dropdown/dropdown.component.html
  src/app/components/dropdown/dropdown.component.scss
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/dropdown/dropdown.component.ts
  src/app/components/icons/icons.component.html
  src/app/components/icons/icons.component.scss
  src/app/components/icons/icons.component.spec.ts
  src/app/components/icons/icons.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.scss
  src/app/components/navigation/navigation.component.spec.ts
  src/app/components/navigation/navigation.component.ts
  src/app/directives/clicked-outside.directive.ts
  src/app/enums/icon.ts
  src/app/interfaces/button.ts
  src/app/interfaces/item.ts
  src/app/lib/Enumerable.ts
  yarn.lock
Labels: enhancement, component

#9 Adv dialog
  package-lock.json
  src/app/app.component.html
  src/app/components/dialog/dialog.component.html
  src/app/components/dialog/dialog.component.scss
  src/app/components/dialog/dialog.component.ts
  src/app/components/dropdown/dropdown.component.html
  src/app/components/dropdown/dropdown.component.scss
  src/app/interfaces/link.ts
Labels: enhancement, component

#11 Configure dependabot
  .github/dependabot.yml
Labels: enhancement

#10 Misc Tasks
  .editorconfig
  .eslintrc.json
  .gitattributes
  .github/dependabot.yml
  .husky/pre-commit
  README.md
  angular.json
  package.json
  scripts/install.ps1
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/code-line/code-line.component.spec.ts
  src/app/components/code-line/code-line.component.ts
  src/app/components/dialog/dialog.component.spec.ts
  src/app/components/dialog/dialog.component.ts
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/dropdown/dropdown.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.scss
  src/app/components/navigation/navigation.component.spec.ts
  src/app/components/navigation/navigation.component.ts
  src/app/components/switch/switch.component.scss
  src/app/components/switch/switch.component.spec.ts
  src/app/components/switch/switch.component.ts
  src/app/data/darkTheme.ts
  src/app/data/lightTheme.ts
  src/app/directives/clicked-outside.directive.ts
  src/app/enums/theme.ts
  src/app/lib/Enumerable.ts
  src/app/lib/utils.ts
  src/app/services/theme-switcher.service.spec.ts
  src/app/services/theme-switcher.service.ts
  src/app/styles/breakpoints.scss
  src/app/styles/theme.scss
  src/app/styles/typography.scss
  src/assets/favicon/dark-16x16.png
  src/assets/favicon/dark-32x32.png
  src/assets/favicon/dark-apple-touch-icon.png
  src/assets/favicon/dark.ico
  src/assets/favicon/light-16x16.png
  src/assets/favicon/light-32x32.png
  src/assets/favicon/light-apple-touch-icon.png
  src/assets/favicon/light.ico
  src/index.html
  src/main.ts
  yarn.lock
Labels: documentation, enhancement
